- name: "Stop Jenkins"
  service: name="jenkins" state="stopped"

- name: Cleanup default work directory
  file:
    path: "{{ jenkins_home }}/*"
    state: absent

- name: Install backup from previous install
  unarchive: 
    src: "{{ backup_location }}"
    dest: "{{ jenkins_home }}"
    owner: "{{ jenkins_config_owner }}"
    mode: 755
    group: "{{ jenkins_config_group }}"
    remote_src: true

- name: Make sure JKS keystore location is created
  file:
    path: "{{ jenkins_home }}/keystore"
    state: directory
    owner: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"
    mode: 755

- name: Setup jenkins config file
  template:
    src: "{{ playbook_dir }}/jenkins-configs/jenkins"
    dest: /etc/sysconfig/jenkins
    mode: 600

- name: Setup TLS and JKS files
  template:
    src: "{{ playbook_dir }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  with_items: "{{ jenkins_cert_files }}"

- name: Copy JKS keystore to jenkins home directory
  copy:
    src: "{{ playbook_dir }}/certs/jenkins.jks"
    dest: "{{ jenkins_home }}/keystore"
    mode: 0644
    owner: "{{ jenkins_config_owner }}"
    group:  "{{ jenkins_config_group }}"

- name: Update trusted ca for redhat
  shell: /bin/update-ca-trust
  when: ansible_os_family == "RedHat"

- name: "Start Jenkins"
  service: name="jenkins" state="started"   
